### ISSUE TITLE
How to implement the same for tiny yolo

### ISSUE THREAD

**Issue by gjraza** [minghuang81/Ultra96-yolo#1]
Hi! I want to do the same implementation on an zynq cpu, but cant seem to get my head around the python to c interface and how you've coded the functions in c. You please tell me how you've implemented these(how are you handling tensors as flat array)? or point me to some resources where i can learn how to?

**Comment by minghuang81** [comment]
Hi, some references below:
1. python to c interface  
The C programs (files suffixed by .c and .h) provides a call interface to Python programs (files suffixed by .py) 
through the C code in ./itf/convNetC_itf.c. C being the "service provider", the interface is thus programmed in C. 

In convNetC_itf.c towards the end, the C functions are packed in a Python module named "convNetC", 
and that module contains only one Python function named "yolo". So the C programms have only a single access point 
(export) to Python, which is convNetC.yolo():  
    Py_InitModule("convNetC", helloworld_funcs);  
    static PyMethodDef helloworld_funcs[] = {  
        {"yolo", (PyCFunction)convNetC_yolo, METH_VARARGS|METH_KEYWORDS, convNetC_docs},  
    
To access the C functions, Python programs call the following Python instructions (see ./test_C.py):  
    from itf import convNetC  
    yolo_evals = convNetC.yolo(resized_image[0],anchors,len(class_names),image_shape)  
    
Tutorials and manuals:
    https://docs.python.org/2/extending/extending.html  
    https://docs.python.org/3/c-api/  
Note the slight difference between Python 2.7 and 3.x, distinguished by "PY3K" keyword in ./itf/convNetC_itf.c  

2. handling tensors as flat array
    https://en.wikipedia.org/wiki/Row-_and_column-major_order  
C programs handle a multidimensional tensor in row-major order. 
For instance, a image is of 2x4 pixels, each pixel in RGB, having a height of 2 pixles and a width of 4, 
in another word the image has two rows and 4 columns. It can be represented by a tensor of shape [2,4,3]:  
    [  
        [[11,12,13],[14,15,16],[17,18,19],[10,11,12]]  
        [[21,22,23],[24,25,26],[27,28,29],[20,21,22]]  
    ]
where [11,12,13] is the top-left pixel and [20,21,22] is the bottom-right pixel.  
The tesor is stored in memory as:
    lower_addr -> 11 12 13 14 15 16 17 18 19 10 11 12 21 22 23 24 25 26 27 28 29 20 21 22  
and can be accessed in C code as lower_addr[0]=11 ... lower_addr[23]=22

**Comment by gjraza** [comment]
Hi! Thanks for the response, are the weights (which are 4d tensors) also stored in the same fashion?
like if i have following filters

[
![image](https://user-images.githubusercontent.com/44520447/59149644-6e4bc200-8a31-11e9-826b-adefc4db60be.png)
](url)

than is this the correct storing order?:
top left pixel               bottom right pixel
[1,5,9,13,17,21..............4,8,12,16,20,24]

**Comment by gjraza** [comment]
Actually I dont intend to use the python interface on my zedboard, so I'll calling the functions directly,
thats why I was trying to pass [this](https://medium.com/@_init_/an-illustrated-explanation-of-performing-2d-convolutions-using-matrix-multiplications-1e8de8cd2544)  example tensor through every function in the net but could'nt match the output

**Comment by gjraza** [comment]
update: I figured it out. Thanks a lot.
